# -*- coding: utf-8 -*-
"""Caesar Cipher CSP2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AMrUTqI8pCsS8paT_eJnUlyzdHCsgXrv
"""

#Variables and chatbot

while True:#repeats until the selection is either 1 or 2
  try:
    select = int(input("Type 1 to encrypt and type 2 to decrypt.\n"))
    if select == 1 or select == 2: #Checks if the number is one of the options (1 or 2)
      break
    else:
      raise ValueError #raises an error if the number is not 1 or 2
  except ValueError:
    print("That is not 1 or 2. Try Again.")

word = input("Give me a word.\n")

while True: #repeats until the input is an integer
  try:
    shift = int(input("Give me an integer to shift your word.\n"))
    if isinstance(shift, int) == True: #checks the type of number of the variable. It makes sure that it is an integer. From w3schools
      break
    else:
      raise ValueError #raises an error if the variable isn't an integer. EX: if it is a word, decimal, etc.
  except ValueError:
    print("That is not an integer. Try again.")

#Functions

def caesar(word, shift, select):
  if select == 1: #if select is 1, it encrypts
    return encrypt(word,shift) #sends off to another function
  elif select == 2: #if select is 2, it decrypts
    return decrypt(word,shift)

def decrypt(word,shift):
  alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'] #alphabet letter list
  new_word = []
  new_str = word.lower() #.lower makes all the letters in the string lowercase (String Method)
  length = len(new_str)
  count = 0
  while count < length:
    if new_str[count] in alphabet: #checks if the character is a letter or a special character
      word_ind = alphabet.index(new_str[count]) #assigns an integer variable to the character's alphabet index (List Method)
      new_word.append(alphabet[(word_ind-shift)% 26]) #.append adds the character to the end of the list (List Method) # If the number goes over 26, the mod makes the number loop back around and use its remainder
    else:
      new_word.append(new_str[count])
    count+=1
  new_message = "".join(new_word)#.join joins the new list and assigns it to a new variable. Also, it removes the brackets and spaces (List Method)
  return new_message

def encrypt(word, shift):
  alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
  new_word = []
  new_str = word.lower()#.lower makes all the letters in the string lowercase (String Method)
  length = len(new_str)
  count = 0
  while count < length:
    if new_str[count] in alphabet:
      abc_ind = alphabet.index(new_str[count]) #assigns an integer variable to the character's alphabet index (List Method)
      new_word.append(alphabet[(abc_ind+shift)% 26]) # If the number goes over 26, the mod makes the number loop back around and use its remainder
    else:
      new_word.append(new_str[count])
    count+=1
  new_message = "".join(new_word)#.join puts the new list into one word and removes the brackets and spaces (List Method)
  return new_message



#Running the function
print(caesar(word, shift,select))